name: http_cache_stream
description: "Simultaneously download, cache, and stream remote content. Perfect for media players and any plugin that streams web content."
version: 0.0.4
homepage: https://github.com/Colton127/http_cache_stream
publish_to: 'none'

platforms:
  android:
  ios:
  linux:
  macos:
  windows:


environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  mime: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  dio: ^5.8.0+1
  util_xx: 
    path: ../util_xx
  string_util_xx: 
    path: ../string_util_xx

dependency_overrides:
  util_xx: 
    path: ../util_xx
  string_util_xx: 
    path: ../string_util_xx

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
